// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	Token        string `json:"token"`
	User         *User  `json:"user"`
	RefreshToken string `json:"refreshToken"`
}

type NewNote struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateNote struct {
	Title   *string `json:"title"`
	Content *string `json:"content"`
}
