// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	Token        string `json:"token"`
	User         *User  `json:"user"`
	RefreshToken string `json:"refreshToken"`
}

type NewNote struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Note struct {
	ID        string `json:"_id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	CreatedAt int    `json:"createdAt"`
	UpdatedAt *int   `json:"updatedAt"`
	CreatedBy *User  `json:"createdBy"`
}

type UpdateNote struct {
	Title   *string `json:"title"`
	Content *string `json:"content"`
}

type User struct {
	ID           string  `json:"_id"`
	Name         string  `json:"name"`
	Email        string  `json:"email"`
	Password     string  `json:"password"`
	CreatedAt    int     `json:"createdAt"`
	UpdatedAt    *int    `json:"updatedAt"`
	Notes        []*Note `json:"notes"`
	RefreshToken *string `json:"refreshToken"`
}
